# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f12474817fce8c6a689109020111534abf3e88d8cda93ccdc5fd2556be7caa9444fbb1080be5ade4b324e399a55d37a8befbe4ce43a3a46bdb62d65d023fb1f

test:
  secret_key_base: a1f2b12a8081dfad31f2c7a72ba3fa5b649037a0ec577a661799bbb8c1c0a720b800379af8102a083d8dcb4b8eabf270fb98e72d170169c6d91ce46099d9f9b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
